### PR TITLE
Refactor pd-extreme e2e tests to re-use existing test cases

### LINKED ISSUE #1117: Refactor pd_extreme_e2e tests to use table-driven tests
The standard and pd_extreme test cases share a lot of similarity. We can parameterize the tests using table-driven tests provided by the ginkgo framework.

https://pkg.go.dev/github.com/onsi/ginkgo@v1.16.5/extensions/table

### PR DESCRIPTION
**Pull request by artemvmin**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
The pd-extreme test cases were originally branched with only minor changes to the test cases. We can use table-driven tests in ginkgo v2 to eliminate the redundancy.

Note: this PR branches from https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1109

**Which issue(s) this PR fixes**:
Fixes #1117

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by artemvmin** [comment]
/unassign @msau42 

Ignore this PR for now I need to polish up the diffbase.

**Comment by artemvmin** [comment]
/assign @msau42 

Ready for review.

**Comment by msau42** [comment]
/lgtm
/approve

Thanks for doing this! I think there are more test cases that can be converted, but I think we could add that to the backlog.

**Pull request merged**
