### PR TITLE
increase node size for 0.5.1 on gke

### PR DESCRIPTION
**Pull request by hantaowang**
**What type of PR is this?**

> /kind failing-test

**What this PR does / why we need it**:
Hopefully fixes flakes for 0.5.1 on gke 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
@davidz627 @jingxu97 

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by davidz627** [comment]
is this a cherry-pick? if so could you put that in the title

**Comment by jingxu97** [comment]
what is the default machine type and what is the difference between those types?

**Comment by jingxu97** [comment]
can you also post the flaky tests link? Thanks!

**Pull request merged**
