### PR TITLE
Add Pod permissions to resizer rbac

### PR DESCRIPTION
**Pull request by saikat-royc**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
/kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Update Resizer RBAC rules to watch pod events
**Which issue(s) this PR fixes**:

Fixes # 531

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Update Resizer RBAC rules to watch pod events
```

### CODE REVIEW

**Comment by msau42** [comment]
/ok-to-test
There's an issue open in resizer to make the new pod watch opt-in.  So we may not need the new rbacs. https://github.com/kubernetes-csi/external-resizer/issues/88

**Comment by mattcary** [comment]
The tests are failing now though, aren't they? Maybe we should get this rbac in and the rollback as appropriate when/if the resizer change is made.

**Comment by msau42** [comment]
The canary job that tests latest, unreleased sidecars is the one that's failing. But we can ask to fix this before the next resizer is released.

**Comment by mattcary** [comment]
> The canary job that tests latest, unreleased sidecars is the one that's failing. But we can ask to fix this before the next resizer is released.

Gotcha. Makes sense to just fix on external-resizer, then, if it's prompt.

**Comment by saikat-royc** [comment]
Closing this PR. As part of https://github.com/kubernetes-csi/external-resizer/issues/88, the watch for Pod events will be feature gated.

**Pull request closed without merging**
