### PR TITLE
Update readme and stable image

### PR DESCRIPTION
**Pull request by hsadoyan**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
The previous stable was 1.7.2 instead of 1.8.1. Is there a specific reason for this, or was it just not updated? Is it safe to update now?

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by leiyiz — COMMENTED** [review]
/lgtm
/approve

**Comment by mattcary** [comment]
/lgtm
/approve

I double-checked that 1.8.2 is in cloud-provider-gcp staging.

@hsadoyan have you made the k8s.io PR to promote the image?

**Comment by hsadoyan** [comment]
> @hsadoyan have you made the k8s.io PR to promote the image?

Yup. The k8s PR is here: https://github.com/kubernetes/k8s.io/pull/4696

**Pull request merged**
