### PR TITLE
Update go version for latest CVE findings

### PR DESCRIPTION
**Pull request by kon-angelo**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Update golang version used for the builder to `v1.19.1` to mitigate latest CVEs.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Go builder updated from 1.18.4 to 1.19.1. 
```

### CODE REVIEW

**Comment by mattcary** [comment]
A question, to update go.sum did you do go mod tidy?

**Comment by kon-angelo** [comment]
@mattcary yes. I did: 
```
go mod tidy
go mod vendor
```

**Comment by mattcary** [comment]
thanks!

/lgtm
/approve

**Pull request merged**
