### PR TITLE
Add separate flags for node and controller and hash nodeId

### PR DESCRIPTION
**Pull request by Sneha-at**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
 /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Adds separate flag to controller data cache feature enablement for node and controller
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Sneha-at** [comment]
/remove-hold Updated test context to accept controller/node flags. Updated logic to fetch NVME disks as `grep` errored out for 0 NVME disks

**Comment by Sneha-at** [comment]
E2E succeeded on local run 
```
.
.
Ran 46 of 48 Specs in 1606.198 seconds
SUCCESS! -- 46 Passed | 0 Failed | 2 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 26m50.476144758s
Test Suite Passed
```

**Comment by mattcary** [comment]
The e2e test failure is weird. Since this is an experimental branch I'll force-merge.

**Pull request merged**
