### PR TITLE
#440 - Updating driver installation documentation

### LINKED ISSUE #440: PKGDIR in setup_project.sh point to sigs.k8s.io instead of github.com/kubernetes-sigs
Hi,

not sure if I tried to clone the driver correctly to my system. I tried to run `go get -v github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver` in order to position it in the `GOPATH` of my cloudshell on GCP.

In this case the `PKGDIR` in `setup_project.sh` points to the wrong location (see [this commit](https://github.com/stiller-leser/gcp-compute-persistent-disk-csi-driver/commit/98d4f7ce157fd30a95e2a19d0159e5f7b3825e3d))

Is this a bug or a user issue? If it is an user issue, could you kindly update [the installation documentation](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/docs/kubernetes/user-guides/driver-install.md) on how to rightly clone the driver to a local system? If not, I'd be happy to contribute my commit as PR.

Best regards,
stiller-leser

### PR DESCRIPTION
**Pull request by stiller-leser**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design

/kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Updates the installation documentation for `gcp-compute-persistent-disk-csi-driver` in order to clarify where the directoy needs to be put on the local machine.

**Which issue(s) this PR fixes**:

Fixes #440 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Documentation update
```

### CODE REVIEW

**Comment by stiller-leser** [comment]
I signed it

**Comment by stiller-leser** [comment]
I signed it

**Comment by msau42** [comment]
/lgtm
/approve
Thanks for updating the docs!

btw, once we move to golang 1.13, I believe we will no longer have this strict requirement on src code location.

**Pull request merged**
