### PR TITLE
Rename master to main

### PR DESCRIPTION
**Pull request by ikarldasan**
**What type of PR is this?**
> /kind documentation

**What this PR does / why we need it**:
Needed for https://github.com/kubernetes/k8s.io/issues/1597

**Which issue(s) this PR fixes**:
Needed for https://github.com/kubernetes/k8s.io/issues/1597

### CODE REVIEW

**Comment by mattcary** [comment]
@ikarldasan It looks like this only effects the promotion process, and not our deployment.

/lgtm

**Comment by mattcary** [comment]
force merging as failures are for known flakes.

**Comment by pohly** [comment]
Hmm, isn't this repo also using the process described in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/release-tools/README.md#sharing-and-updating?

Direct modifications to `release-tools` then should be avoided.

**Pull request merged**
