### PR TITLE
cherry pick #1085 #1087 and #1094 to release-1.8

### PR DESCRIPTION
**Pull request by leiyiz**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
cherry pick #1085 to be included in release-1.8

sanity tests are failing so picking #1087 and #1094 in as well.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Logging for gRPC call is now limited to 10000 char by default, and configurable with flag --grpc-log-char-cap
```

### CODE REVIEW

**Comment by leiyiz** [comment]
looking into the sanity test failure, it seems that sanity test depend on https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/commit/7435b75ce0c82e244f9cbc81cd96264535f19967 and that commit in turns have merge conflicts with release-1.8 branch. I think it makes more sense to cut 1.9 branch to include this fix.

**Comment by leiyiz** [comment]
@mattcary PTAL again

**Comment by mattcary** [comment]
/lgtm
/approve

Ah, the sanity test fix wasn't as big as we feared.

**Comment by leiyiz** [comment]
> Ah, the sanity test fix wasn't as big as we feared.

yeah I was trying to also include 7435b75ce0c82e244f9cbc81cd96264535f19967 which generated a lot of dependencies. It turns out to be not necessary.

**Pull request merged**
