### PR TITLE
E2E Testing Framework Changes for PROW Pre-Submits

### PR DESCRIPTION
**Pull request by davidz627**
Fixes: #14

### CODE REVIEW

**Comment by msau42** [comment]
You have the name change commit included here too

**Comment by davidz627** [comment]
@msau42 I'm just trying to layer commits until I get CI to pass right now. Not sure exactly what is borking it

**Comment by davidz627** [comment]
/assign @msau42 
It isn't pretty right now but pre-submits are running both CSI Sanity and the E2E Tests!!
I will submit PR later this week cleaning it up a little.
New issue tracking cleanup #29

**Comment by msau42** [comment]
/lgtm
Woot :-)

**Pull request merged**
