### PR TITLE
Automated cherry pick of #1666: migrate hyperdisk/chd/storagepools to GCE v1 disk API
#1667: remove support for GCE Alpha Disks

### PR DESCRIPTION
**Pull request by amacaskill**
Cherry pick of #1666 #1667 on release-1.13.

#1666: migrate hyperdisk/chd/storagepools to GCE v1 disk API
#1667: remove support for GCE Alpha Disks

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Migrate Hyperdisk/CHD/StoragePools to GCE v1 disk API, and remove support for GCE alpha disk API.
```

### CODE REVIEW

**Comment by sunnylovestiramisu** [comment]
For the integ tests, the build failed.

**Comment by amacaskill** [comment]
> For the integ tests, the build failed.

Its also failing in another PR I have. It isn't related to this change. The error is `(gcloud.compute.instances.create) Must specify either [--image] or [--image-family] when specifying [--image-project] flag.`

**Pull request merged**
