### PR TITLE
Automated cherry pick of #1084: Upgrade klog v1 to v2 and fix error wrapping

### PR DESCRIPTION
**Pull request by sunnylovestiramisu**
Cherry pick of #1084 on release-1.7.

#1084: Upgrade klog v1 to v2 and fix error wrapping

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Upgrade klog v1 to v2 and fix error wrapping
```

### CODE REVIEW

**Comment by amacaskill** [comment]
Can you add this PR to the release czar doc for PDCSI R13 that we need a 1.7 minor release which includes this cherry pick PR?

**Comment by sunnylovestiramisu** [comment]
I already added to R13.

**Comment by msau42** [comment]
Didn't we have to update some flag initialization? When I compare the driver logs from [this run](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_gcp-compute-persistent-disk-csi-driver/1216/pull-gcp-compute-persistent-disk-csi-driver-kubernetes-integration/1655979986370170880/artifacts/pd-csi-driver/csi-gce-pd-node-8g5f9-gce-pd-driver.log) vs a [previous run](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_gcp-compute-persistent-disk-csi-driver/1210/pull-gcp-compute-persistent-disk-csi-driver-kubernetes-integration/1650607312403959808/artifacts/pd-csi-driver/csi-gce-pd-node-bdj22-gce-pd-driver.log) on this branch, I see some logs are missing in this PR's run, for example

```
I0424 21:36:57.550657       1 mount_linux.go:408] Disk "/dev/disk/by-id/google-pvc-c90a6290-072d-4751-895a-0a68eb1e0d50" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/disk/by-id/google-pvc-c90a6290-072d-4751-895a-0a68eb1e0d50]
```

**Comment by sunnylovestiramisu** [comment]
> Didn't we have to update some flag initialization? When I compare the driver logs from [this run](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_gcp-compute-persistent-disk-csi-driver/1216/pull-gcp-compute-persistent-disk-csi-driver-kubernetes-integration/1655979986370170880/artifacts/pd-csi-driver/csi-gce-pd-node-8g5f9-gce-pd-driver.log) vs a [previous run](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_gcp-compute-persistent-disk-csi-driver/1210/pull-gcp-compute-persistent-disk-csi-driver-kubernetes-integration/1650607312403959808/artifacts/pd-csi-driver/csi-gce-pd-node-bdj22-gce-pd-driver.log) on this branch, I see some logs are missing in this PR's run, for example
> 
> ```
> I0424 21:36:57.550657       1 mount_linux.go:408] Disk "/dev/disk/by-id/google-pvc-c90a6290-072d-4751-895a-0a68eb1e0d50" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/disk/by-id/google-pvc-c90a6290-072d-4751-895a-0a68eb1e0d50]
> ```

The klog.InitFlags(flag.CommandLine) is already in the code. And the other run seems calling a lot of NodePublishVolume check volume path but this one does not hmmm.

**Comment by sunnylovestiramisu** [comment]
Ohh. I got it, you were looking at the log of a node that does not have the operations:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_gcp-compute-persistent-disk-csi-driver/1216/pull-gcp-compute-persistent-disk-csi-driver-kubernetes-integration/1655979986370170880/artifacts/pd-csi-driver/csi-gce-pd-node-mfvv5-gce-pd-driver.log

**Comment by msau42** [comment]
Thanks my bad.

/lgtm
/approve

**Pull request merged**
