### PR TITLE
update klog version to latest. change %w unwrap to %v

### PR DESCRIPTION
**Pull request by leiyiz**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
in order to bump klog version, `%w` is no longer supported. `%v` should be used instead

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Error wrapping for `klog` logging is changed from `%w` to `%v` due to klog version bump.
```

### CODE REVIEW

**Comment by leiyiz** [comment]
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1575 updates klog but `%w` is no longer supported.

**Comment by sunnylovestiramisu** [comment]
Does this worth make a note in release notes?

**Comment by leiyiz** [comment]
> Does this worth make a note in release notes?

Yeah I think that makes sense

**Pull request merged**
