### PR TITLE
Add backoff for detach/attach

### PR DESCRIPTION
**Pull request by saikat-royc**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
1.  Adding back the backoff logic for detach call which was removed in #923
2. Adding backoff for the attach call too.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mattcary** [comment]
lgtm, but the e2e test failures look interesting.

**Comment by pwschuurman** [comment]
LGTM

**Pull request closed without merging**
