### PR TITLE
fix test focus

### PR DESCRIPTION
**Pull request by msau42**
The test naming has changed

Fixes: #146

### CODE REVIEW

**Comment by davidz627** [comment]
looks like we have actual test failures :(

**Comment by msau42** [comment]
Yes I think the test is timing out because it's all run serially. I'm trying to make it run in parallel

**Comment by davidz627** [comment]
/retest
to see if it was a parallelism problem
from looking at the test results my hunch is there is something else going on too

**Comment by davidz627** [comment]
Failing tests:
```
I1114 22:00:35.173] Summarizing 2 Failures:
I1114 22:00:35.173] 
I1114 22:00:35.174] [Fail] [sig-storage] CSI Volumes [Driver: com.google.csi.gcepd][Feature: gcePD-external] [Testpattern: Dynamic PV (default fs)] subPath [It] should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow] 
I1114 22:00:35.174] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/utils/utils.go:212
I1114 22:00:35.174] 
I1114 22:00:35.174] [Fail] [sig-storage] CSI Volumes [Driver: com.google.csi.gcepd][Feature: gcePD-external] [Testpattern: Dynamic PV (default fs)] subPath [It] should unmount if pod is force deleted while kubelet is down [Disruptive][Slow] 
I1114 22:00:35.174] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/utils/utils.go:212
```

From a cursory look the errors seem to be: 
```
Encountered SSH error.
I1114 21:56:42.430]       Expected error:
I1114 21:56:42.430]           <*errors.errorString | 0xc0009dc480>: {
I1114 21:56:42.430]               s: "error getting signer for provider gce: 'error reading SSH key /root/.ssh/google_compute_engine: 'open /root/.ssh/google_compute_engine: no such file or directory''",
I1114 21:56:42.431]           }
I1114 21:56:42.431]           error getting signer for provider gce: 'error reading SSH key /root/.ssh/google_compute_engine: 'open /root/.ssh/google_compute_engine: no such file or directory''
I1114 21:56:42.431]       not to have occurred
```

seems like the code to bring the Kubelet down needs to do an SSH into the cluster and we don't have the required keys for that

**Comment by davidz627** [comment]
/retest
It should work this time since driver name changed and prow head template have been updated

**Pull request merged**
