### PR TITLE
Update prepull image agnhost version

### PR DESCRIPTION
**Pull request by jingxu97**
Update agnhoost version

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jingxu97** [comment]
pull-gcp-compute-persistent-disk-csi-driver-e2e-win2019

**Comment by jingxu97** [comment]
@msau42 The windows test fails one or two test due to some other issues.  It is not related to this PR. I think we can merge this one so most of the tests pass timeout issue. Thanks!

**Comment by msau42** [comment]
whoops accidentally closed

**Pull request merged**
