### PR TITLE
Add opentelemetry tracing on gRPC calls for self-managed drivers

### LINKED ISSUE #1299: Add otel trace instrumentation on gRPC calls
**Is your feature request related to a problem? Please describe.**
Add some more observability to the csi driver. In particular, add gRPC tracing using opentelemetry. 

**Describe the solution you'd like in detail**
We implemented it in [our fork](https://github.com/DataDog/gcp-compute-persistent-disk-csi-driver/pull/2). So I can submit a similar PR here.
The feature is working as expected and we are able to get the gRPC traces.

**Describe alternatives you've considered**
None

**Additional context**
We did a similar instrumentation in [aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1714) and [azuredisk-csi-driver](https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1912)

### PR DESCRIPTION
**Pull request by Fricounet**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test

/kind feature

> /kind flake

**What this PR does / why we need it**:
Allow self-managed drivers to add basic tracing on the gRPC calls received by the driver (controller and node) using opentelemetry. This is useful to help monitor and debug driver issues on top of existing logs.
Otel tracing can be enabled using the flag `--enable-otel-tracing`. Defaults to `false`.

**Which issue(s) this PR fixes**:
Fixes #1299 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Added enable-otel-tracing flag to enable opentelemetry tracing for self-managed drivers. The flag is disabled by default
```

### CODE REVIEW

**Comment by Fricounet** [comment]
cc @mattcary, I finally got the time to submit the PR

**Comment by Fricounet** [comment]
@mattcary could you take a look at this PR? :pray:

**Comment by mattcary** [comment]
Sorry for the delay in looking at this, we got backed up behind some issues. I'll take a look.

**Comment by mattcary** [comment]
/lgtm
/approve

I'll probably need to re-lgtm after you resolve the merge conflict.

**Comment by Fricounet** [comment]
thanks for your review, I just rebased the PR :)

**Pull request merged**
