### PR TITLE
Remove verult from OWNERS files

### PR DESCRIPTION
**Pull request by verult**
```release-note
None
```

/triage accepted
/kind cleanup

### CODE REVIEW

**Comment by mattcary** [comment]
:-(

/retest
/lgtm

**Comment by mattcary** [comment]
Prow is having problems with authentication, we'll try again later.

It doesn't want you to leave either, Cheng!

**Comment by verult** [comment]
😭 😭 😭 😭 😭

**Comment by saikat-royc** [comment]
:(

**Pull request merged**
