### PR TITLE
[WIP] Add E2E test artifact directory

### PR DESCRIPTION
**Pull request by davidz627**
Fixes: #188

### CODE REVIEW

**Comment by davidz627** [comment]
going to put this on hold since I can't seem to figure out who actually defines "--report-dir". I can't find it documented anywhere, its not in k8s/k8s, k8s/test-infra, or ginkgo (???)

**Comment by msau42** [comment]
https://github.com/kubernetes/kubernetes/blob/a3ccea9d8743f2ff82e41b6c2af6dc2c41dc7b10/test/e2e/framework/test_context.go#L223

**Comment by davidz627** [comment]
no idea why my code search failed to bring up that file. Will look into it later

**Comment by davidz627** [comment]
Made the required changes but the artifact upload is puzzling me. what it looks like is `gsutil` is finding the `junit.xml` file then trying to upload it then immediately complaining that the file doesn't exist. (???)

**Comment by msau42** [comment]
cc @krzyzacy

**Comment by krzyzacy** [comment]
log link?

**Comment by davidz627** [comment]
> log link?

https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_gcp-compute-persistent-disk-csi-driver/189/pull-gcp-compute-persistent-disk-csi-driver-e2e/357/

**Comment by davidz627** [comment]
/remove-lifecycle rotten
maybe some day I will have time to revisit this

**Pull request closed without merging**
