### PR TITLE
v1.3.1 changelog

### PR DESCRIPTION
**Pull request by mattcary**
Update changelog for v1.3.1 release.

/assign @saikat-royc 
/kind documentation

```release-note
None
```

### CODE REVIEW

**Comment by saikat-royc** [comment]
the master https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/CHANGELOG/CHANGELOG-1.3.md is out of date. We should first update the master branch CHANGELOG-1.3 and then cherry pick to release-1.3

**Comment by mattcary** [comment]
Good point. I'll just make a separate PR for the master branch, the
cherry-pick will look the same as this PR anyway.

**Comment by mattcary** [comment]
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/820 created for the master

**Pull request merged**
