### PR TITLE
update stable master and README reference to 1.7.2

### PR DESCRIPTION
**Pull request by leiyiz**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
we are cutting 1.7.2 release

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mattcary** [comment]
The snapshot test is still failing due to https://github.com/kubernetes/kubernetes/issues/110645, let's wait for that to be fixed before pushing this change (we can update the sidecars in the deployment at the same time too).

**Comment by leiyiz** [comment]
@mattcary can you lgtm this now that all the tests passed

**Pull request merged**
