### PR TITLE
Pre v0.4.0 release docs and staging image changes

### PR DESCRIPTION
**Pull request by davidz627**
/assign @msau42

### CODE REVIEW

**Comment by davidz627** [comment]
The ordering I'm thinking of is this:
1) Merge this PR which will make docs and staging images out of date temporarily (staging tests will begin to fail)
2) Tag the commit as v0.4.0
3) Release tooling will publish v0.4.0 staging images
4) Monitor staging tests for success.
5) On staging test success, push another change updating stable container images and cherry-pick to release branch v0.4.0

**Comment by msau42** [comment]
> 5\. On staging test success, push another change updating stable container images and cherry-pick to release branch v0.4.0

Then would we have to tag a 0.4.1 that has the stable container image changes?

**Comment by davidz627** [comment]
/hold
until rc tagged and soaked

**Comment by davidz627** [comment]
/close
docs not ready

**Pull request closed without merging**
