### PR TITLE
Updating changelog for release v1.11.0, v1.10.6, v1.9.8, v1.8.9 v1.7.11

### PR DESCRIPTION
**Pull request by pwschuurman**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Update release specific changelog for recent gcp-compute-persistent-disk-csi-driver releases

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by sunnylovestiramisu** [comment]
Can you rebase? The e2e test should be fixed after rebase.

**Comment by pwschuurman** [comment]
> Can you rebase? The e2e test should be fixed after rebase.

I think we can just retest. The test failed as it checked out commit hash "9d0a7329581440885233c002d716af8433dc0ae2", which was one before your change was merged in.

**Pull request merged**
