### PR TITLE
Cherrypick #644, #647, #652 from `master` to `release-1.1`

### PR DESCRIPTION
**Pull request by saad-ali**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
/kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Cherrypick #647 from `master` to `release-1.1`: Update kustomizer to 3.8.6
Cherrypick #644 from `master` to `release-1.1`: Add release notes for 1.1.0 release
Cherrypick #652 from `master` to `release-1.1`: Update staging RC to use new 1.1.0 RC build

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

/assign @jingxu97 
/assign @msau42

### CODE REVIEW

**Comment by saad-ali** [comment]
Test failed:

```
W1031 00:30:45.400] F1031 00:30:45.399921    3277 main.go:161] Failed to run integration test: failed to install CSI Driver: failed to install kustomize: installing kustomize
W1031 00:30:45.401] curl: no URL specified!
W1031 00:30:45.401] curl: try 'curl --help' or 'curl --manual' for more information
W1031 00:30:45.402] , err: exit status 123
W1031 00:30:45.416] Traceback (most recent call last):
W1031 00:30:45.417]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W1031 00:30:45.417]     main(ARGS.env, ARGS.cmd + ARGS.args)
W1031 00:30:45.418]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W1031 00:30:45.418]     check(*cmd)
W1031 00:30:45.418]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W1031 00:30:45.419]     subprocess.check_call(cmd)
W1031 00:30:45.419]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W1031 00:30:45.419]     raise CalledProcessError(retcode, cmd)
W1031 00:30:45.419] subprocess.CalledProcessError: Command '('test/run-k8s-integration.sh',)' returned non-zero exit status 255
E1031 00:30:45.452] Command failed
I1031 00:30:45.453] process 630 exited with code 1 after 34.9m
E1031 00:30:45.454] FAIL: pull-gcp-compute-persistent-disk-csi-driver-kubernetes-integration
```

Per https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/649 the fix is in #647 -- that PR should be cherry picked to the release branch first.

**Comment by jingxu97** [comment]
this is caused by kustimization release download does not include 3.8.0 which we specified in the script. I already fix it in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/647

**Comment by saad-ali** [comment]
Added #647 to the cherry pick.
PTAL

**Pull request merged**
