### PR TITLE
Enable kubelet-registration-probe mode in node-driver-registrar in Windows & Linux

### PR DESCRIPTION
**Pull request by mauriciopoppe**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
/kind feature

**What this PR does / why we need it**:
Adds support for https://github.com/kubernetes-csi/node-driver-registrar/pull/152 on Windows & Linux nodes, I tried patching previous releases to remove the probe configuration because it was introduced in node-driver-registrar v2.3.0

The output for `kustomize build deploy/kubernetes/overlays/stable-1-19` is ok (liveness probe should be removed because the version is less than v2.3.0): 

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-gce-pd-node-win
  namespace: gce-pd-csi-driver
spec:
  selector:
    matchLabels:
      app: gcp-compute-persistent-disk-csi-driver
  template:
    metadata:
      labels:
        app: gcp-compute-persistent-disk-csi-driver
    spec:
      containers:
      - args:
        - --v=5
        - --csi-address=unix://C:\\csi\\csi.sock
        - --kubelet-registration-path=C:\\var\\lib\\kubelet\\plugins\\pd.csi.storage.gke.io\\csi.sock
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
        name: csi-driver-registrar
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /registration
          name: registration-dir
```

Also the output for `kustomize build deploy/kubernetes/overlays/stable` is ok:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-gce-pd-node-win
  namespace: gce-pd-csi-driver
spec:
  selector:
    matchLabels:
      app: gcp-compute-persistent-disk-csi-driver
  template:
    metadata:
      labels:
        app: gcp-compute-persistent-disk-csi-driver
    spec:
      containers:
      - args:
        - --v=5
        - --csi-address=unix://C:\\csi\\csi.sock
        - --kubelet-registration-path=C:\\var\\lib\\kubelet\\plugins\\pd.csi.storage.gke.io\\csi.sock
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
        livenessProbe:
          exec:
            command:
            - /csi-node-driver-registrar.exe
            - --kubelet-registration-path=C:\\var\\lib\\kubelet\\plugins\\pd.csi.storage.gke.io\\csi.sock
            - --mode=kubelet-registration-probe
          initialDelaySeconds: 3
        name: csi-driver-registrar
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /registration
          name: registration-dir
```

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/cc @jingxu97 @msau42

### CODE REVIEW

**Comment by mauriciopoppe** [comment]
@jingxu97 after a discussion with the managed PD CSI team this PR is updating files that are obsolete (`stable` overlay), for the other overlays I think that the output is ok as shown in the description

/cc @saikat-royc

**Comment by jingxu97** [comment]
update the title and commit message?

/lgtm

**Comment by mauriciopoppe** [comment]
> update the title and commit message?

done, thanks :)

**Comment by saikat-royc** [comment]
stable folder is deprecated, instead stable-<minor version>, stable-master should be updated.

**Comment by mauriciopoppe** [comment]
stable-master is already using v2.3.0 added in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/828, @saikat-royc I can remove the change in `stable/` if needed

**Comment by saikat-royc** [comment]
/hold

We should added the changes to prow overlays first and ensure the prow runs suceeded. And when the tests are green,  we also need to add to stable-master and other stable-* overlays.

**Comment by mauriciopoppe** [comment]
@saikat-royc I've added `no-node-driver-registrar-probe.yaml` to `stable-master` too, please take a look

**Pull request merged**
