### PR TITLE
Fix syntax error on the common script

### LINKED ISSUE #493: deploy/common.sh has a syntax error on `ensure_var`
**Description**
When running `setup_project.sh` the following syntax error shows up:
`${GOPATH}/src/sigs.k8s.io/gcp-compute-persistent-disk-csi-driver/deploy/common.sh: line 11: conditional binary operator expected`

### PR DESCRIPTION
**Pull request by clebs**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Fixes a syntax issue on the `deploy/common.sh` script when checking for unset variables.

**Which issue(s) this PR fixes**:

Fixes #493 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
None of the variables I see `ensure_var` used with are expected to be empty. So I think this is fine.

/lgtm
/approve

**Comment by clebs** [comment]
Thanks for the quick review and merge @msau42!

**Pull request merged**
