### PR TITLE
Update driver to use csi proxy filesystem v1beta1

### PR DESCRIPTION
**Pull request by jingxu97**
1 Update driver to use lastest csi proxy with filesystem v1beta1
2 Update csi-proxy vendor
3 Update psp for windows to use v1beta1 for filesystem pipe
4 update service account for windows

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jingxu97** [comment]
cc @msau42

**Comment by mattcary** [comment]
Looks like the v1beta for filesystem isn't updated in vendor?

**Comment by jingxu97** [comment]
> Looks like the v1beta for filesystem isn't updated in vendor?

my mistake. forgot to git add those files..

**Comment by jingxu97** [comment]
cc @mattcary I added vendor file. PTAL. Thanks!

**Comment by mattcary** [comment]
It doesn't look like those windows e2e tests have much history? Maybe windows machines need more startup time or whatever & the timeouts are too low?

**Comment by jingxu97** [comment]
I think that's because I recently changed the test name to have version information. The tests now are broken I need to fix some multi-arch build issue.

**Comment by jingxu97** [comment]
cc @mattcary @msau42 PTAL. thanks!

**Comment by mattcary** [comment]
/lgtm

Sure, sgtm

**Pull request merged**
