### PR TITLE
Gke integration cherrypicks

### LINKED ISSUE #337: Cherrypick GKE Integration test support into release-0.5.X
/cc @davidz627

### PR DESCRIPTION
**Pull request by hantaowang**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR cherry-picks all the changes made to the integration test suite that allows the test to boot a GKE cluster into release-0.5.X.

**Which issue(s) this PR fixes**:
Fixes #337 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
None
```

### CODE REVIEW

**Comment by davidz627** [comment]
looks like there may be some gofmt error

**Comment by hantaowang** [comment]
@davidz627 @jingxu97 ready for review thanks!

**Comment by hantaowang** [comment]
note that the presubmit job here still runs on gce because the default is still gce.

**Pull request merged**
