### PR TITLE
[WIP] Add logging for CreateSnapshot that already exists

### PR DESCRIPTION
**Pull request by amacaskill**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by mattcary** [comment]
Add a release note then lgtm

/lgtm
/approve

**Comment by amacaskill** [comment]
> Add a release note then lgtm
> 
> /lgtm /approve

Was just going to let this run on the PR, then hopefully can figure what's going on then make a fix.

**Comment by mattcary** [comment]
Oh, I see. Yeah, good idea.

/remove-approve

**Pull request closed without merging**
