### PR TITLE
Support partitions in VolumeAttributes

### PR DESCRIPTION
**Pull request by davidz627**
Fixes: #83 

Tested with Kubernetes and it works.
The deployment yamls used:
https://gist.github.com/davidz627/ae1d3071913eda1f6dacfe59779073cf

/assign @msau42

### CODE REVIEW

**Comment by msau42** [comment]
I'm surprised your yaml works. The pods are likely to be scheduled to 2 different nodes

**Comment by davidz627** [comment]
@msau42 It was just for a quick test so I got lucky. But yea in a real situation you'd want to nodeselector

**Pull request merged**
