### PR TITLE
fixes kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#913

### LINKED ISSUE #913: Fix Volume Snapshot from Pre-Existing Snapshot doc
## Issue Description

The existing [snapshot.md](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/docs/kubernetes/user-guides/snapshots.md) documentation, especially the section `Import a Pre-Existing Snapshot` does not work as is.

## Acceptance Criteria

I suggest to fix it, taking inspiration from the Kubernetes-csi repo and [resource definitions](https://github.com/kubernetes-csi/external-snapshotter/blob/master/client/apis/volumesnapshot/v1/types.go).

### PR DESCRIPTION
**Pull request by damien75**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
/kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: this fixes a documentation that doesn't accomplish the goal of creating a volume snapshot from an existing snapshot

**Which issue(s) this PR fixes**: Fixes #913 

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: NONE

```release-note

```

### CODE REVIEW

**Comment by mattcary** [comment]
/ok-to-test
@leiyiz can you take a look at this & verify?

**Review by leiyiz — CHANGES_REQUESTED** [review]
L#180 `$SNAPSHOT_ID` should be `SNAPSHOT_NAME`

L#173 should be `VolumeSnapshotContent` instead of `VolumeSnapshotContents`

**Comment by leiyiz** [comment]
LGTM, please squash your commits as well :)

**Comment by mattcary** [comment]
Thanks for reviewing Leiyi!

/lgtm
/approve

**Pull request merged**
