### PR TITLE
Cherrypick #682,  #684, #693, #703, #718, #719, #720 to release-1.2 from master

### PR DESCRIPTION
**Pull request by saikat-royc**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
 /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Cherrypick #682,  #684, #693, #703, #718, #719, #720 to release-1.2 from master

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mattcary** [comment]
Can we add #718 as well? Note there have been two label PRs.

**Comment by saikat-royc** [comment]
> Can we add #718 as well? Note there have been two label PRs.

Yes on it now. I realized that while testing the changes locally

**Pull request merged**
