### PR TITLE
Update docs for v1.0.1 release

### PR DESCRIPTION
**Pull request by saad-ali**
**What type of PR is this?**
kind cleanup

**What this PR does / why we need it**:
Update docs to reflect upcoming v1.0.1 release.
Link will not work until release process is complete.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by msau42** [comment]
/hold
CHANGELOG?

**Comment by saad-ali** [comment]
@msau42 Added CHANGELOG.
PTAL

**Pull request merged**
