### PR TITLE
Use v1.9.0-rc3

### PR DESCRIPTION
**Pull request by sunnylovestiramisu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
rc3 has more fixes: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/compare/master...release-1.9

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE

```

/assign @saikat-royc

### CODE REVIEW

**Comment by sunnylovestiramisu** [comment]
Baking: https://k8s-testgrid.appspot.com/provider-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Latest%20Release%20Candidate

**Comment by saikat-royc** [comment]
note: we need a rc-3 for https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1142

**Comment by sunnylovestiramisu** [comment]
And we need this: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1144

**Review by leiyiz — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
