### PR TITLE
Add Windows jobs for stable-1.18, 1.19 and master

### PR DESCRIPTION
**Pull request by jingxu97**
Add Windows jobs to stable overlays

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by saikat-royc** [comment]
Thanks for making the changes. Couple of nits:
1. Can you also change the prow-gke-release-staging-rc-{k8sversion} to use stable-{k8sversion} as resource base again.  (I had pointed them to ../../base to easily inherit the windows changes from base) https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-18/kustomization.yaml
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-19/kustomization.yaml
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/deploy/kubernetes/overlays/prow-gke-release-staging-rc-master/kustomization.yaml
and also verify that kustomize build works (e.g kustomize build ./deploy/kubernetes/overlays/prow-gke-release-staging-rc-master/)

2. Can you also change the  test/run-windows-k8s-integration.sh (and other related windows test scripts) to point to stable-master by default in this PR? or you plan to do that in a separate patch?
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/test/run-windows-k8s-integration.sh#L13
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/test/run-k8s-windows-migration.sh#L15

**Comment by jingxu97** [comment]
> Thanks for making the changes. Couple of nits:
> 
> 1. Can you also change the prow-gke-release-staging-rc-{k8sversion} to use stable-{k8sversion} as resource base again.  (I had pointed them to ../../base to easily inherit the windows changes from base) https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-18/kustomization.yaml
>    https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-19/kustomization.yaml
>    https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/deploy/kubernetes/overlays/prow-gke-release-staging-rc-master/kustomization.yaml
>    and also verify that kustomize build works (e.g kustomize build ./deploy/kubernetes/overlays/prow-gke-release-staging-rc-master/)
> 2. Can you also change the  test/run-windows-k8s-integration.sh (and other related windows test scripts) to point to stable-master by default in this PR? or you plan to do that in a separate patch?
>    https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/test/run-windows-k8s-integration.sh#L13
>    https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/test/run-k8s-windows-migration.sh#L15

I updated accordingly. I see overlay stable is exactly the same as stable-master? Do we need two?

**Comment by saikat-royc** [comment]
> table is exactly the same as stable-master

stable and prow-gke-release-staging-rc will be removed once all the test jobs have switched to use stable-master and prow staging new overlays

**Comment by saikat-royc** [comment]
can we also update:
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/deploy/kubernetes/overlays/prow-gke-release-staging-rc-master/kustomization.yaml
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/test/run-k8s-windows-migration.sh#L15

**Pull request merged**
