### PR TITLE
Use v0.7.0 image for release-0.7

### LINKED ISSUE #687: XFS tests failing in 0.7 testgrid
https://testgrid.k8s.io/provider-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Release%200.7

It seems to be because the v0.6.2 driver image used in this release does not contain the xfs tools.

That's a little weird, because it appears the v0.6.2 release was cut after the xfs tools were added to the docker image. Inspecting the v0.6.2 image shows the tools are definitely not included, so there you have it.

I think the fix is just to use v0.7.0 in release-0.7, which I would have thought should have been done from the start?

/assign @mattcary

### PR DESCRIPTION
**Pull request by mattcary**
/kind bug

**Which issue(s) this PR fixes**:
Fixes #687

/assign @msau42 

```release-note
NONE
```

### CODE REVIEW

**Comment by mattcary** [comment]
/assign @verult 

Michelle is out for the holidays. Cheng, do you have any context on release-0.7?

**Comment by verult** [comment]
/lgtm
/approve

This should've been updated as part of the release process so yeah definitely looks like a bug to me, although if no one noticed this bug, I'm wondering how important it really is to keep per-release deployment specs up-to-date.

**Comment by mattcary** [comment]
Oh, I see. OWNERS on this branch is old and I'm not in it. Michelle or Saad, can you approve?

/assign @msau42 
/cc @saad-ali

**Pull request merged**
