### PR TITLE
Bumping all images to latest versions for 0.6.0 stable release

### PR DESCRIPTION
**Pull request by verult**
Sidecar images are available in gcr.io/gke-release.

```release-note
NONE
```

/assign @davidz627 @msau42

### CODE REVIEW

**Comment by davidz627** [comment]
Please also update the README

**Comment by verult** [comment]
Updated README. Holding while I run tests on a 1.14 cluster to verify compatibility.

/hold

**Comment by verult** [comment]
Integration tests against 1.14.6 cluster passed

/hold cancel

**Comment by davidz627** [comment]
/lgtm
/approve
Thanks for testing. When this PR merges I will tag and release v0.6.0

**Comment by davidz627** [comment]
@verult Please add a release note

**Pull request merged**
