### PR TITLE
Cherrypick #658 from `master` to `release-1.1` 

### PR DESCRIPTION
**Pull request by saad-ali**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Cherrypick #658 from master to release-1.1: Update docs/stable overlay to reference new release

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

/assign @msau42

### CODE REVIEW

**Comment by saad-ali** [comment]
PTAL

**Comment by saad-ali** [comment]
> why I cannot trigger windows test?

Is it configured for the release branch?

**Comment by jingxu97** [comment]
> > why I cannot trigger windows test?
> 
> Is it configured for the release branch?

oh, got it. it is for release branch.

**Pull request merged**
