### PR TITLE
Remove make from verify-all in order to reduce presubmit flakes

### PR DESCRIPTION
**Pull request by mattcary**
/kind cleanup
**Does this PR introduce a user-facing change?**:

```release-note
None
```

/assign @amacaskill

### CODE REVIEW

**Comment by pwschuurman** [comment]
@mattcary Do you have an example of a verify presubmit flake where `make` is failing?

From what I've seen the verify presubmit started failing ~2 weeks ago, and times out running the verify-docker-deps command (running on ARM architecture with QEMU). I think #1878 should fix this problem.

**Comment by mattcary** [comment]
> @mattcary Do you have an example of a verify presubmit flake where `make` is failing?
> 
> From what I've seen the verify presubmit started failing ~2 weeks ago, and times out running the verify-docker-deps command (running on ARM architecture with QEMU). I think #1878 should fix this problem.

verify-docker-deps is run during the docker bulid which is run as part of the make?

#1878 seems like a good idea, so we should do it too, but since we also build as part of the e2e I'm not sure what the value of running make as part of the verify is.

Having verify focus on the go code seems like a nice understandable and contained step to do. Fiddling with the build process seems like a different thing.

**Comment by pwschuurman** [comment]
> Having verify focus on the go code seems like a nice understandable and contained step to do. Fiddling with the build process seems like a different thing.

Gotcha, agreed. Yeah, I think it's reasonable to remove.

**Comment by mattcary** [comment]
Hmm, although with #1878 we will no longer verify dependencies as part of presubmit. That's a bug.

**Comment by mattcary** [comment]
Ah, so actually I'm timing out in the verify docker deps which also runs make. So even more reason not to run make again?

**Comment by mattcary** [comment]
I picked up Peter's fix and will retest.

/retest

**Pull request merged**
